### ISSUE TITLE
Use cases and storage

### ISSUE THREAD

**Issue by asad-awadia** [claygod/transaction#2]
I had two questions @claygod 

1. What kind of use cases is this library trying to help build?

2. Is everything held in memory? Is data lost when the process ends?

**Comment by claygod** [comment]
This library is for memory use only. If the computer is shut down due to electricity, all data will be lost. In order for the data not to be lost, you can use two identical services, and if one goes out, then the other is alive.

Those. here, only stopping and saving from the code will allow you not to lose data.

If it is very important for you that, even with a power outage, the data is intact and consistent, then pay attention to another library: [https://github.com/claygod/coffer](https://github.com/claygod/coffer)

This library has interesting examples on the financial topic: purchase, translation. It is interesting in that it allows you to create custom procedures that the library will call. Considering that the library maintains a transaction log, it is a very fast library.
